const TRADING_PAIRS: any = {
  BNBUSDT: 'BNBUSDT',
  BTCUSDT: 'BTCUSDT',
  ETHUSDT: 'ETHUSDT',
  LTCUSDT: 'LTCUSDT',
  XRPUSDT: 'XRPUSDT',
  ADAUSDT: 'ADAUSDT',
  SOLUSDT: 'SOLUSDT',
  DOTUSDT: 'DOTUSDT',
} as const;

export default TRADING_PAIRS;
